version: 0.3.6.{build}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: >-
    msbuild Sichem.Framework\Sichem.Framework.csproj /p:Configuration=Release /t:rebuild

    nuget restore Sichem.Framework\Sichem.Framework.NETStandard.csproj

    msbuild Sichem.Framework\Sichem.Framework.NETStandard.csproj /p:Configuration=Release /t:rebuild

    nuget pack Sichem.Framework\Sichem.Framework.nuspec -Version %APPVEYOR_BUILD_VERSION%
artifacts:
  - path: Sichem.Framework.$(appveyor_build_version).nupkg
    name: Sichem.Framework.nupkg
deploy:
  - provider: NuGet
    api_key:
      secure: o02Abc+1Pg/C7FVPnbCA9i4RIakmOUcKjMBBCHDCbEhS69b+N05mV0xBe0ne2/Y4
    artifact: /.*\.nupkg/